### ISSUE TITLE
Servo pulses for zero degrees

### ISSUE THREAD

**Issue by allanx17** [KitronikLtd/micropython-microbit-kitronik-robotics#2]
The robotics.py 'def servoWrite' generates zero length pulses for a turning angle of zero degrees. This should be a 1 ms pulse (which it does for 90 degrees). The main issue is in the formula for PWMVal, where self.SERVO_ZERO_OFFSET should be outside the brackets, and also have a value for 1 ms of 4096 /20 for 50 Hz.

**Comment by JackAtKitronik** [comment]
Hey, thanks for pointing out the problem with our servo code.

It has now been updated to perform the calculation in the correct order.

To learn more about servos and how they work check out this [blog post](https://kitronik.co.uk/blogs/resources/servos-brief-guide).
